### PR TITLE
Fix barbed wires 

### PR DESCRIPTION
**Pull request by ProfElements**
This should be the proper fix for barbed wires. Just get the direction from the block to the entity and apply a large amount of force that way

### CODE REVIEW

**Comment by TerslenK** [comment]
prof is back 👀

**Comment by J3fftw1** [comment]
Hey prof,
Are you back if so we can pr all changes to your repo so you can continue.
You branch is also still the one pointing to the buids server.
Let us know
Also thanks for the pr appreciate it.

**Comment by ProfElements** [comment]
>  Are you back

No. I just had a little time and wanted to do something productive while I had it. 

 >  You branch is also still the one pointing to the buids server.

My branch wont be updated for months at a time and I dont have the time to maintain it so y'all can change it to point to this.

**Comment by J3fftw1** [comment]
Thanks for the pr anyways i will review it when im home.
Let me or sefi know if you want to be added to the repo as maintainier so if you decide to come back you can take over

**Pull request closed without merging**
